# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_page.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QMainWindow, QPushButton, QSizePolicy,
    QWidget)
from Images_for_design import background_imgs_rc
from Images_for_design import static_img_rc
from Images_for_design import interactable_image_source_rc

class Ui_main_page(object):
    def setupUi(self, main_page):
        if not main_page.objectName():
            main_page.setObjectName(u"main_page")
        main_page.resize(794, 586)
        self.centralwidget = QWidget(main_page)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 151, 591))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 80, 151, 511))
        self.label.setStyleSheet(u"background-image: url(:/backgournds/FlyTranslate-logo/background_image.png);")
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, -20, 151, 111))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet(u"background-image: url(:/backgournds/FlyTranslate-logo/logo_only_2.png);")
        self.label_6.setScaledContents(False)
        self.btnMainButton = QPushButton(self.frame)
        self.btnMainButton.setObjectName(u"btnMainButton")
        self.btnMainButton.setGeometry(QRect(0, 90, 151, 51))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btnMainButton.setFont(font)
        self.btnMainButton.setAutoFillBackground(True)
        self.btnMainButton.setCheckable(True)
        self.btnMainButton.setChecked(True)
        self.btnRunTimeSettings = QPushButton(self.frame)
        self.btnRunTimeSettings.setObjectName(u"btnRunTimeSettings")
        self.btnRunTimeSettings.setGeometry(QRect(0, 140, 151, 51))
        self.btnRunTimeSettings.setFont(font)
        self.btnRunTimeSettings.setAutoFillBackground(True)
        self.btnRunTimeSettings.setCheckable(True)
        self.btnRunTimeSettings.setChecked(False)
        self.btnProfileSettings = QPushButton(self.frame)
        self.btnProfileSettings.setObjectName(u"btnProfileSettings")
        self.btnProfileSettings.setGeometry(QRect(0, 190, 151, 51))
        self.btnProfileSettings.setFont(font)
        self.btnProfileSettings.setAutoFillBackground(True)
        self.btnProfileSettings.setCheckable(True)
        self.btnProfileSettings.setChecked(False)
        self.btnFAQ = QPushButton(self.frame)
        self.btnFAQ.setObjectName(u"btnFAQ")
        self.btnFAQ.setGeometry(QRect(0, 240, 151, 51))
        self.btnFAQ.setFont(font)
        self.btnFAQ.setAutoFillBackground(True)
        self.btnFAQ.setCheckable(True)
        self.btnFAQ.setChecked(False)
        self.btnLogout = QPushButton(self.frame)
        self.btnLogout.setObjectName(u"btnLogout")
        self.btnLogout.setGeometry(QRect(0, 535, 151, 51))
        self.btnLogout.setFont(font)
        self.btnLogout.setAutoFillBackground(True)
        self.btnLogout.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u":/logout/logout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnLogout.setIcon(icon)
        self.btnLogout.setCheckable(False)
        self.btnLogout.setChecked(False)
        self.btnFeedback = QPushButton(self.frame)
        self.btnFeedback.setObjectName(u"btnFeedback")
        self.btnFeedback.setGeometry(QRect(0, 290, 151, 51))
        self.btnFeedback.setFont(font)
        self.btnFeedback.setAutoFillBackground(True)
        self.btnFeedback.setCheckable(True)
        self.btnFeedback.setChecked(False)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(153, 0, 641, 591))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 131, 16))
        font1 = QFont()
        font1.setFamilies([u"Rockwell"])
        font1.setPointSize(11)
        font1.setItalic(True)
        self.label_4.setFont(font1)
        self.lblUsername = QLabel(self.frame_2)
        self.lblUsername.setObjectName(u"lblUsername")
        self.lblUsername.setGeometry(QRect(20, 40, 431, 21))
        font2 = QFont()
        font2.setFamilies([u"Rockwell"])
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setItalic(True)
        self.lblUsername.setFont(font2)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 811, 591))
        self.label_2.setStyleSheet(u"background-image: url(:/backgournds/FlyTranslate-logo/background_image.png);")
        self.label_2.setScaledContents(True)
        self.cbbSource = QComboBox(self.frame_2)
        self.cbbSource.setObjectName(u"cbbSource")
        self.cbbSource.setGeometry(QRect(95, 270, 171, 31))
        self.cbbTarget = QComboBox(self.frame_2)
        self.cbbTarget.setObjectName(u"cbbTarget")
        self.cbbTarget.setGeometry(QRect(385, 270, 171, 31))
        self.label_5 = QLabel(self.frame_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(385, 240, 161, 21))
        self.label_5.setFont(font)
        self.lblbtnSwapLanguage = QLabel(self.frame_2)
        self.lblbtnSwapLanguage.setObjectName(u"lblbtnSwapLanguage")
        self.lblbtnSwapLanguage.setGeometry(QRect(310, 270, 31, 31))
        self.lblbtnSwapLanguage.setPixmap(QPixmap(u":/can_switch/swap.png"))
        self.lblbtnSwapLanguage.setScaledContents(True)
        self.label_3 = QLabel(self.frame_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(95, 240, 161, 21))
        self.label_3.setFont(font)
        self.btnSaveConfig = QPushButton(self.frame_2)
        self.btnSaveConfig.setObjectName(u"btnSaveConfig")
        self.btnSaveConfig.setGeometry(QRect(210, 340, 231, 41))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(True)
        self.btnSaveConfig.setFont(font3)
        self.btnSaveConfig.setCheckable(False)
        self.btnCropImage = QPushButton(self.frame_2)
        self.btnCropImage.setObjectName(u"btnCropImage")
        self.btnCropImage.setGeometry(QRect(140, 160, 131, 51))
        self.btnCropImage.setFont(font3)
        self.btnCropImage.setCheckable(False)
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 400, 621, 16))
        font4 = QFont()
        font4.setStrikeOut(True)
        self.label_11.setFont(font4)
        self.btnMinimize = QPushButton(self.frame_2)
        self.btnMinimize.setObjectName(u"btnMinimize")
        self.btnMinimize.setGeometry(QRect(220, 510, 211, 41))
        self.btnMinimize.setFont(font3)
        icon1 = QIcon()
        icon1.addFile(u":/minimize/minimize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnMinimize.setIcon(icon1)
        self.btnMinimize.setCheckable(False)
        self.lblTipsLang = QLabel(self.frame_2)
        self.lblTipsLang.setObjectName(u"lblTipsLang")
        self.lblTipsLang.setGeometry(QRect(575, 270, 31, 31))
        self.lblTipsLang.setStyleSheet(u"image: url(:/tips/information.png);")
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 420, 581, 81))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(True)
        font5.setStyleStrategy(QFont.PreferDefault)
        self.label_8.setFont(font5)
        self.label_8.setLineWidth(1)
        self.label_8.setMidLineWidth(0)
        self.label_8.setWordWrap(True)
        self.label_8.setMargin(0)
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 100, 401, 31))
        self.label_9.setFont(font)
        self.cbToggleScanFullScreen = QCheckBox(self.frame_2)
        self.cbToggleScanFullScreen.setObjectName(u"cbToggleScanFullScreen")
        self.cbToggleScanFullScreen.setGeometry(QRect(540, 100, 61, 41))
        self.cbToggleScanFullScreen.setAutoFillBackground(False)
        self.cbToggleScanFullScreen.setStyleSheet(u"QCheckBox::indicator:unchecked{\n"
"	image: url(:/not-toggled/off-button.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"	image: url(:/toggled/on-button.png);\n"
"}")
        self.cbToggleScanFullScreen.setChecked(False)
        self.cbToggleScanFullScreen.setTristate(False)
        self.btnTestOutputImageSize = QPushButton(self.frame_2)
        self.btnTestOutputImageSize.setObjectName(u"btnTestOutputImageSize")
        self.btnTestOutputImageSize.setGeometry(QRect(370, 160, 131, 51))
        self.btnTestOutputImageSize.setFont(font3)
        self.btnTestOutputImageSize.setCheckable(False)
        self.lblTipsScan = QLabel(self.frame_2)
        self.lblTipsScan.setObjectName(u"lblTipsScan")
        self.lblTipsScan.setGeometry(QRect(575, 170, 31, 31))
        self.lblTipsScan.setStyleSheet(u"image: url(:/tips/information.png);")
        self.label_2.raise_()
        self.label_4.raise_()
        self.lblUsername.raise_()
        self.cbbSource.raise_()
        self.cbbTarget.raise_()
        self.label_5.raise_()
        self.lblbtnSwapLanguage.raise_()
        self.label_3.raise_()
        self.btnSaveConfig.raise_()
        self.btnCropImage.raise_()
        self.label_11.raise_()
        self.btnMinimize.raise_()
        self.lblTipsLang.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.cbToggleScanFullScreen.raise_()
        self.btnTestOutputImageSize.raise_()
        self.lblTipsScan.raise_()
        main_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_page)

        QMetaObject.connectSlotsByName(main_page)
    # setupUi

    def retranslateUi(self, main_page):
        main_page.setWindowTitle(QCoreApplication.translate("main_page", u"MainWindow", None))
        self.label.setText("")
        self.label_6.setText("")
        self.btnMainButton.setText(QCoreApplication.translate("main_page", u"Main Page", None))
        self.btnRunTimeSettings.setText(QCoreApplication.translate("main_page", u"Runtime Setting", None))
        self.btnProfileSettings.setText(QCoreApplication.translate("main_page", u"Profile Setting", None))
        self.btnFAQ.setText(QCoreApplication.translate("main_page", u"FAQ", None))
        self.btnLogout.setText(QCoreApplication.translate("main_page", u"  Log out", None))
        self.btnFeedback.setText(QCoreApplication.translate("main_page", u"Feedback", None))
        self.label_4.setText(QCoreApplication.translate("main_page", u"Welcome Back,", None))
        self.lblUsername.setText(QCoreApplication.translate("main_page", u"SAMPLEUSERNAME!!", None))
        self.label_2.setText("")
        self.label_5.setText(QCoreApplication.translate("main_page", u"Target Language:", None))
        self.lblbtnSwapLanguage.setText("")
        self.label_3.setText(QCoreApplication.translate("main_page", u"Source Language:", None))
        self.btnSaveConfig.setText(QCoreApplication.translate("main_page", u"Save current configurations", None))
        self.btnCropImage.setText(QCoreApplication.translate("main_page", u"Crop Area", None))
        self.label_11.setText(QCoreApplication.translate("main_page", u"----------------------------------------------------------------------------------------------------------------------------", None))
        self.btnMinimize.setText(QCoreApplication.translate("main_page", u"Minimize application", None))
        self.lblTipsLang.setText("")
        self.label_8.setText(QCoreApplication.translate("main_page", u"<html><head/><body><p>To translate screen text, minimize application first for best experience: </p><p>(It will hang for a while if it's initializing or downloading language resources) (No need to force stop if it hangs, please wait for the program to initialize.)</p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("main_page", u"<html><head/><body><p>Scan full screen without crop:</p></body></html>", None))
        self.cbToggleScanFullScreen.setText("")
        self.btnTestOutputImageSize.setText(QCoreApplication.translate("main_page", u"Preview output \n"
"image size", None))
        self.lblTipsScan.setText("")
    # retranslateUi

