# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'register_page.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QWidget)
from Images_for_design import interactable_image_source_rc
from Images_for_design import background_imgs_rc

class Ui_register_page(object):
    def setupUi(self, register_page):
        if not register_page.objectName():
            register_page.setObjectName(u"register_page")
        register_page.resize(553, 590)
        self.centralwidget = QWidget(register_page)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-40, -320, 701, 911))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"background-image: url(:/backgournds/FlyTranslate-logo/background_image.png);")
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 531, 571))
        font = QFont()
        font.setFamilies([u"Rockwell"])
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"")
        self.label_2.setFrameShape(QFrame.Box)
        self.label_2.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 110, 101, 16))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 160, 101, 16))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 370, 101, 16))
        self.label_5.setFont(font1)
        self.txtUsername = QLineEdit(self.centralwidget)
        self.txtUsername.setObjectName(u"txtUsername")
        self.txtUsername.setGeometry(QRect(210, 100, 231, 31))
        self.txtEmail = QLineEdit(self.centralwidget)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setGeometry(QRect(210, 150, 231, 31))
        self.txtPass = QLineEdit(self.centralwidget)
        self.txtPass.setObjectName(u"txtPass")
        self.txtPass.setGeometry(QRect(210, 360, 191, 31))
        self.txtPass.setEchoMode(QLineEdit.Password)
        self.lblbtnViewOrHidePass = QLabel(self.centralwidget)
        self.lblbtnViewOrHidePass.setObjectName(u"lblbtnViewOrHidePass")
        self.lblbtnViewOrHidePass.setGeometry(QRect(400, 360, 41, 31))
        self.lblbtnViewOrHidePass.setCursor(QCursor(Qt.PointingHandCursor))
        self.lblbtnViewOrHidePass.setStyleSheet(u"image: url(:/view/view.png);")
        self.lblbtnViewOrHidePass.setFrameShape(QFrame.Panel)
        self.btnBack = QPushButton(self.centralwidget)
        self.btnBack.setObjectName(u"btnBack")
        self.btnBack.setGeometry(QRect(150, 200, 101, 41))
        self.btnBack.setFont(font1)
        self.btnRegisterAcc = QPushButton(self.centralwidget)
        self.btnRegisterAcc.setObjectName(u"btnRegisterAcc")
        self.btnRegisterAcc.setGeometry(QRect(230, 490, 111, 41))
        self.btnRegisterAcc.setFont(font1)
        self.lblbtnViewOrHidePass_2 = QLabel(self.centralwidget)
        self.lblbtnViewOrHidePass_2.setObjectName(u"lblbtnViewOrHidePass_2")
        self.lblbtnViewOrHidePass_2.setGeometry(QRect(400, 420, 41, 31))
        self.lblbtnViewOrHidePass_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.lblbtnViewOrHidePass_2.setStyleSheet(u"image: url(:/view/view.png);")
        self.lblbtnViewOrHidePass_2.setFrameShape(QFrame.Panel)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 410, 111, 41))
        self.label_6.setFont(font1)
        self.label_6.setTextFormat(Qt.PlainText)
        self.label_6.setWordWrap(True)
        self.txtConfirmPass = QLineEdit(self.centralwidget)
        self.txtConfirmPass.setObjectName(u"txtConfirmPass")
        self.txtConfirmPass.setGeometry(QRect(210, 420, 190, 31))
        self.txtConfirmPass.setEchoMode(QLineEdit.Password)
        self.btnSendOTP = QPushButton(self.centralwidget)
        self.btnSendOTP.setObjectName(u"btnSendOTP")
        self.btnSendOTP.setGeometry(QRect(310, 200, 111, 41))
        self.btnSendOTP.setFont(font1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(100, 290, 51, 16))
        self.label_7.setFont(font1)
        self.txtOTP = QLineEdit(self.centralwidget)
        self.txtOTP.setObjectName(u"txtOTP")
        self.txtOTP.setGeometry(QRect(210, 280, 101, 31))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 250, 511, 16))
        font2 = QFont()
        font2.setStrikeOut(True)
        self.label_8.setFont(font2)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 320, 511, 16))
        self.label_9.setFont(font2)
        self.btnVerifyOTP = QPushButton(self.centralwidget)
        self.btnVerifyOTP.setObjectName(u"btnVerifyOTP")
        self.btnVerifyOTP.setGeometry(QRect(410, 275, 111, 41))
        self.btnVerifyOTP.setFont(font1)
        self.lblTipsOTP = QLabel(self.centralwidget)
        self.lblTipsOTP.setObjectName(u"lblTipsOTP")
        self.lblTipsOTP.setGeometry(QRect(320, 280, 31, 31))
        self.lblTipsOTP.setStyleSheet(u"image: url(:/tips/information.png);")
        register_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(register_page)

        QMetaObject.connectSlotsByName(register_page)
    # setupUi

    def retranslateUi(self, register_page):
        register_page.setWindowTitle(QCoreApplication.translate("register_page", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText(QCoreApplication.translate("register_page", u"Register New Account", None))
        self.label_3.setText(QCoreApplication.translate("register_page", u"Username:", None))
        self.label_4.setText(QCoreApplication.translate("register_page", u"Email:", None))
        self.label_5.setText(QCoreApplication.translate("register_page", u"Password:", None))
        self.lblbtnViewOrHidePass.setText("")
        self.btnBack.setText(QCoreApplication.translate("register_page", u"Back", None))
        self.btnRegisterAcc.setText(QCoreApplication.translate("register_page", u"Register", None))
        self.lblbtnViewOrHidePass_2.setText("")
        self.label_6.setText(QCoreApplication.translate("register_page", u"Confirm Password:", None))
        self.btnSendOTP.setText(QCoreApplication.translate("register_page", u"Send OTP", None))
        self.label_7.setText(QCoreApplication.translate("register_page", u"OTP:", None))
        self.label_8.setText(QCoreApplication.translate("register_page", u"------------------------------------------------------------------------------------------------------", None))
        self.label_9.setText(QCoreApplication.translate("register_page", u"------------------------------------------------------------------------------------------------------", None))
        self.btnVerifyOTP.setText(QCoreApplication.translate("register_page", u"Verify OTP", None))
        self.lblTipsOTP.setText("")
    # retranslateUi

